version: '3.7'

services:
  server:
    restart: "no"
    build:
      context: ssh_build
    hostname: "server.ssh"
    volumes:
      - ./authorized_keys/first_fido_ssh_key.pub:/home/user/.ssh/authorized_keys
    expose:
      - "22"

networks:
  default:
    external:
      name: fido-ssh-test

